### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by liqingqing-lqq** [wangxiang4/loquat-form-design#1]
Error in data(): "TypeError: Cannot read properties of undefined (reading 'createMessage')"
 Error in render: "TypeError: Cannot read properties of undefined (reading 'length')"
 
 <loquat-form-design v-if="visible"
                        ref="loquat-form-design"
                        style="height:calc(100vh - 133px)"
                        :toolbar="['clear', 'preview']"
                        :options="options"
                        :custom-fields="customFields"
    />

data () {
    return {
      visible: false,
      loading: false,
      options: {column: []},
      customFields: [{
        title: '自定义字段',
        list: [
          {
            title: '分割线',
            type: 'custom',
            component: 'el-divider',
            icon: 'iconfont icon-divider',
            label: '',
            propExclude: true,
            labelWidth: 0,
            params: {
              html: '<h3 style="color:red">分割线标题</h3>',
              contentPosition: 'left'
            }
          },
          {
            title: '警告',
            type: 'custom',
            component: 'el-alert',
            icon: 'el-icon-warning',
            label: '',
            propExclude: true,
            labelWidth: 0,
            params: {
              title: '警告警告警告警告',
              type: 'success'
            },
            events: {
              close () {
                console.log('alert关闭事件')
              }
            }
          }
        ]
      }],
      form: {}
    }
  },

**Comment by wangxiang4** [comment]
current repaired
vue3 form designer is currently being rewritten, current it is possible to use the micro-front-end approach to introduce [qiankun-loquat-form-design](https://www.npmjs.com/package/qiankun-loquat-form-design) 
vue2 can be used  [loquat-form-design](https://www.npmjs.com/package/loquat-form-design)
